backend = "LLVM"

[llvm]
llc_path = "/usr/local/opt/llvm/bin/llc"
llc_args = []

[assembler]
nasm_args = ["-g", "-f", "macho64", "-F", "dwarf"]

[linker]
linker_path = "ld"
linker_args = [
    "-arch", "x86_64", "-platform_version", "macos", "10.15", "10.15",
    "/usr/lib/libSystem.dylib",
    "../target/debug/libruntime.a",
]
